isPublic: true
name: 'Public Schema'
scope:
  - 'sites.dabb80e6-8dc1-4d79-838f-e45c676d1db3:read' # Formie Starters
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'usergroups.solo:read'
  - 'formieForms.all:read'
  - 'formieForms.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:read'
  - 'formieForms.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:read'
  - 'formieForms.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:read'
  - 'formieSubmissions.all:read'
  - 'formieSubmissions.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:read'
  - 'formieSubmissions.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:read'
  - 'formieSubmissions.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:read'
  - 'formieSubmissions.all:edit'
  - 'formieSubmissions.all:create'
  - 'formieSubmissions.all:save'
  - 'formieSubmissions.all:delete'
  - 'formieSubmissions.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:edit'
  - 'formieSubmissions.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:create'
  - 'formieSubmissions.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:save'
  - 'formieSubmissions.c5c26b24-57c5-4f36-817d-07c3bdbc01ee:delete'
  - 'formieSubmissions.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:edit'
  - 'formieSubmissions.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:create'
  - 'formieSubmissions.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:save'
  - 'formieSubmissions.8aa2ad87-56bc-443a-aeb7-3dba0c5bc492:delete'
  - 'formieSubmissions.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:edit'
  - 'formieSubmissions.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:create'
  - 'formieSubmissions.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:save'
  - 'formieSubmissions.16d2b0bf-0d0d-4831-b4a8-9c97b5a17061:delete'
